### ISSUE TITLE
Please add install instructions

### ISSUE THREAD

**Issue by unixorn** [Gary-Ash/SnazzyPrompt#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have installation instructions.

Thanks!

**Comment by Gary-Ash** [comment]
I thought I had put some instructions in there.
I've added a copy of my ZSH setup

**Comment by unixorn** [comment]
How does someone build the binary?

**Comment by Gary-Ash** [comment]
As a Mac person, I use the Xcode project but maybe I could add a Cmake or something. If I get time this weekend I do something and then fix the Read Me markdown
